# Generated by Django 5.0.4 on 2024-05-06 13:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ecommerce", "0002_alter_item_name_alter_transaction_transaction_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="transaction_id",
            field=models.CharField(
                default="e4a901eb-7f94-4b82-8c8d-58858ef08e2e",
                max_length=100,
                unique=True,
            ),
        ),
    ]
