# Generated by Django 5.0.4 on 2024-05-06 16:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ecommerce", "0003_alter_transaction_transaction_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transaction",
            name="amount",
        ),
        migrations.AlterField(
            model_name="transaction",
            name="transaction_id",
            field=models.CharField(default="242bcfcf-ef8a-46bd-88f9-9b9132eb1fb3", max_length=100, unique=True),
        ),
    ]
